### ISSUE TITLE
Feature request:  scalar()

### ISSUE THREAD

**Issue by pjz** [kennethreitz/records#105]
IWBNI, when requesting a single value from a single row, there was a way to return that value directly.  Currently the best we can do is:
```
   db.query(somequery).first()[0]
```
I'd propose some sugar, just to make things look neater:
```
  db.query(somequery).scalar()
```

Though I guess I can monkeypatch it for now.

**Comment by vlcinsky** [comment]
Resolved. PR #147 contains test case for it and it is passing.
