### ISSUE TITLE
Records silently ignores duplicate field name in joined tables. 

### ISSUE THREAD

**Issue by mjmare** [kennethreitz/records#108]
In an SQL query I had joined to tables that happened to have a field with the same name (with different content). Records selected one of the fields without complaining; it just happened to be the wrong one. 

```sql
SELECT *
FROM A LEFT OUTER JOIN B on A.somekey=B.somekey
WHERE .....
```
If A and B contain a field with the same name, just one is returned. Usually the table name is prefixed to distinguish them, but I assume Records just uses the fieldname without prefix. That is usually convenient but not in this case. I think I'd prefer an error message.

**Comment by KUR-creative** [comment]
Still not working. Even exception does not be raised.

My code:
```python
def get(query, user, pw, host, port, dbname):
    connection = f'{user}:{pw}@{host}:{port}/{dbname}'
    conn_url = f'postgresql+psycopg2://{connection}'
    db = records.Database(conn_url)
    return db.query(str(query))

# usage
query = '''SELECT f1.relpath, f2.relpath FROM file as f1, file as f2'''
rows = get(query, *connection)

for r in rows:
    print(r)
```

The result:
```
<Record {"relpath": "clean_wk/61.png"}>
<Record {"relpath": "clean_wk/62.png"}>
<Record {"relpath": "clean_wk/63.png"}>
<Record {"relpath": "clean_wk/64.png"}>
<Record {"relpath": "clean_wk/65.png"}>
<Record {"relpath": "clean_wk/66.png"}>
<Record {"relpath": "clean_wk/67.png"}>
<Record {"relpath": "clean_wk/68.png"}>
<Record {"relpath": "clean_wk/69.png"}>
...
```
In this case, it seems to be necessary to distinguish columns by table name as a prefix.
ex) `<Record {"f1.relpath": ..., "f2.relpath": ...}>`
