### ISSUE TITLE
How could I run a SQL background?

### ISSUE THREAD

**Issue by leafonsword** [kennethreitz/records#124]
I want to run a DDL and a DML, while DDL takes a long time, so I want to  put DDL background running, and run DML forground; But belowing code will run DDL and after DDL ends then run DML:
```
conn.query(f'alter table sbtest3 engine=innodb,algorithm=copy;') 
conn.query(f'insert into sbtest3 values(3);') 
```

**Comment by Tethik** [comment]
If I'm understanding this right, you want to run the first statement concurrently with the second statement. Did you try using threading, multiprocessing or an asynchronous library like asyncio?

**Comment by leafonsword** [comment]
@Tethik Thx, I'm using concurrent.futures now~
