### ISSUE TITLE
Would it be possible to issue a new release?

### ISSUE THREAD

**Issue by charlax** [kennethreitz/records#131]
The lazy connection feature added in fe0ed3199dd952d57bfa12ecdb6c69acd1c98ece is critical for many use case (e.g. an API). Would you be so kind as to release a new version of records that contains it?

Thanks, Kenneth.

Charles

**Comment by charlax** [comment]
Well, I presume this is blocked on #128.

**Comment by jian-en** [comment]
I am also waiting for the new release. I tried to change it but feel challenging. BTW, I use flask and if i change back to sqlalchemy, it needs more work.

**Comment by jian-en** [comment]
![image](https://user-images.githubusercontent.com/11342080/37454176-d2ca8862-2874-11e8-9a51-7a972869670d.png)
Temporarily I add a param to control the db connection. :(

**Comment by Tethik** [comment]
@vlcinsky What's the status on this? Been almost a year since release at this point.

**Comment by vlcinsky** [comment]
@Tethik we have to ask @kennethreitz as he is probably the only person, who can publish new version to pypi.

I am watching @kennethreitz via git repo of his [journal](https://github.com/kennethreitz/journal/commits/master) as the commits simply track his latest activities there. Unfortunately his latest entry is somewhere in May.

It would really help this (and related) projects to have backup maintainer (who could publish to pypi too), but I do not want to repeat myself (all is already mentioned in #144)

**Comment by Tethik** [comment]
Alright, thanks. Is there still any work we could or need to do before a new version is release ready?

**Comment by nkantar** [comment]
It appears this has been merged and new releases have been issued since the last activity here. Candidate for closing?
