### ISSUE TITLE
race condition between ResultSet's all() and __iter__()

### ISSUE THREAD

**Issue by hrldcpr** [kennethreitz/records#14]
If you partially iterate over a ResultSet, and then call `all()`, it will return only what has been iterated over so far, not "all rows" as specified, i.e. something like:
```python
rows = db.query('select * from active_users')
it = iter(rows)
print(next(it))  # row 1
print(rows.all())  # [row 1]
print(next(it))  # row 2
print(rows.all())  # [row 1, row 2]
```

A simple fix would be:
```python
def all(self):
    # If rows aren't cached, fetch them.
    if not self._completed:
        self._all_rows.extend(self._rows)
        self._completed = True
    return self._all_rows
```

…but I have a feeling there will be a more elegant solution once you've fixed #13 :car:

**Comment by kennethreitz** [comment]
This was just fixed by https://github.com/kennethreitz/records/pull/22

Thanks for reporting!
