### ISSUE TITLE
Drop python2.6 support

### ISSUE THREAD

**Issue by vlcinsky** [kennethreitz/records#141]
Trying to run tests under python 2.6 is printing DEPRECATION warnings.

Python 2.6 also does not run with latest version of SQLAlchemy package.

Proposal: drop support for python2.6 as it is not supported by core python team.

**Comment by vlcinsky** [comment]
[tablib already dropped python 2.6](https://github.com/kennethreitz/tablib/commit/5dd74c0104789b2019c97f863e597369ccfed108)

**Comment by hugovk** [comment]
👍 

Here's the pip installs for records from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  52.47% |          1,720 |
| 3.6            |  30.54% |          1,001 |
| 3.5            |   8.66% |            284 |
| 3.4            |   8.30% |            272 |
| 2.6            |   0.03% |              1 |

Source: `pypinfo --start-date -46 --end-date -16 --percent --pip --markdown records pyversion`

**Comment by hugovk** [comment]
Please see PR #146.

**Comment by kennethreitz** [comment]
@vlcinsky up for the task? :)
