### ISSUE TITLE
ORM

### ISSUE THREAD

**Issue by laith43d** [kennethreitz/records#159]
Why don’t we turn this great project into a fully fledged ActiveRecord implementation?
I mean Kenneth is genius in making his project apis human friendly, this would end up a huge thing!

**Comment by Tethik** [comment]
I like this library for the exact opposite reason: that it's not an ORM and I can run my SQL queries with some help. I think the design goal of the library was just that too. Check the first sentences of the readme:

> Just write SQL. No bells, no whistles. This common task can be surprisingly difficult with the standard tools available. This library strives to make this workflow as simple as possible, while providing an elegant interface to work with your query results.

For a python ORM there is already [peewee](http://docs.peewee-orm.com/en/latest/) or [sqlalchemy](https://www.sqlalchemy.org/), which are both pretty good.

**Comment by vlcinsky** [comment]
I completely agree with @Tethik 
To keep things "human friendly" one shall have well defined scope and stay within.
