### ISSUE TITLE
Maybe it's worth to make a version for the terminal?

### ISSUE THREAD

**Issue by andrew-tifon** [kennethreitz/records#17]
Sometimes it is convenient without touching the database view table or take data in .json, .html, .csv, .yaml or .xls
Write the script for this for a long time, but these programs do not have to Unix
So users can be given together with a library of more quick way to import and export tables

**Comment by andrew-tifon** [comment]
Well, you know like this
```Shell
$ records --path ~/bd/test.sql --formar csv
```
and is ready, the table in the desired format

**Comment by andrew-tifon** [comment]
and make exports from the file into the table
```Shell
$ records export --path ~/test.csv
```

**Comment by kennethreitz** [comment]
I like this idea, very much!

**Comment by kennethreitz** [comment]
Print results out to console:
```$ records myquery.sql```

Print results as JSON out to console:
```$ records myquery.sql --json``` 
or maybe
```$ records myquery.sql json```

Add parameters (for parameterized queries):
```$ records myquery.sql language=python```

Export functionality:
```$ records myquery.sql csv language=python > data.csv```

**Comment by andrew-tifon** [comment]
what do you mean (language=python) ?
```Shell
$ records myquery.sql language=python
```

**Comment by kennethreitz** [comment]
@andrew-tifon `language` is a parameter to the query.

**Comment by andrew-tifon** [comment]
It's param=None ?
Database.query(query, param=None ...)

**Comment by kennethreitz** [comment]
@andrew-tifon updated my example :)

**Comment by kennethreitz** [comment]
Okay, I worked on this last night. Got the help string down with usage/etc. 

```
Records: SQL for Humans™
A Kenneth Reitz project.

Usage:
  records <query> [<format>] [--url=<url>] [--params <params>...]
  records (-h | --help)

Options:
  -h --help    Show this screen.
  --url=<url>  The database URL to use. Defaults to $DATABASE_URL.
  --params     Prameterized query. Subsequent arguments are treated as
               parameters to the query.

Supported Formats:
   csv, tsv, json, yaml, html, xls, xlsx, dbf, latex, ods

   Note: xls, xlsx, dbf, and ods formats are binary, and should only be
         used with piped output e.g. '$ records sql xls > sql.xls'.

Notes:
  - While you may specify a Postgres connection string with --url, records
    will automatically default to the value of $DATABASE_URL, if available.
  - Query is intended to be the path of a SQL file, however a query string
    can be provided instead. Use this feature discernfully; it's dangerous.
  - Records is intended for report-style exports of database queries, and
    has not yet been optimized for extremely large data dumps.

Cake:
   ✨ 🍰 ✨
```

**Comment by timofurrer** [comment]
Looks great - super simple and easy to use!

What I miss here is, that everything is about exporting data, right?
Or at least when specifying the *[<format>]*. However, it may not be obvious to anyone - I really like when it's all self-explained - This could be done with providing an `export` command and option. (I know import is not supported but, so it's export - but anyway. Importing seems to be a cool feature for the future).

One small thing:
> Note: xls, xlsx, dbf, and ods formats are binary, and should only be
>        used with piped output e.g. '$ records sql xls > sql.xls'.

That's a *redirect* not *pipe*.

**Comment by kennethreitz** [comment]
Relased!
