### ISSUE TITLE
Do you plan to add support for MySQL?

### ISSUE THREAD

**Issue by dwj300** [kennethreitz/records#2]

**Comment by kennethreitz** [comment]
No. Maybe. 

Postgres is definitely my preferred database, and I consider the use of it to be best practice. However, I also see that this is a totally great library for running queries at, say, your company, left and right. Those databases could be running postgres, mysql, oracle, or a number of others. 

My biggest priority is keeping the API as clean as possible. Ideally, the codebase would be the same way. The only way I could really see going whole-hog *let's support everything* is to swap out the current psycopg2 layer with SQLAlchemy, and use it purely for the database driver. I'm not sure how feasible this is, but based on my work on [Django-PostgresPool](https://github.com/kennethreitz/django-postgrespool), I think it should be pretty doable.

**Comment by kennethreitz** [comment]
Currently, this library plans to support Postgres–only. That may change, but not now.

**Comment by kennethreitz** [comment]
*cough* support for MySQL has been added!

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

v0.4.0 includes support for all major databases. Enjoy!

**Comment by whit537** [comment]
This can be closed again. ;-)
