### ISSUE TITLE
neutralize README text

### ISSUE THREAD

**Issue by unbracketed** [kennethreitz/records#20]
A couple sentences toward the end start with "Of course", but the sentences could IMO be rewritten without those parts:

> Of course, all other features of Tablib are also available

> Of course, the recommended installation method is pip:

Removing "Of course" from those sentences still conveys the same amount of information.  The README, as currently written, contains things that are obvious to you, but might not be to the casual reader. 

As always, thanks for the great work

**Comment by kennethreitz** [comment]
Hmmm, the first one could use some work. I like the second one, though.
