### ISSUE TITLE
Is records being maintained?

### ISSUE THREAD

**Issue by sri-rang** [kennethreitz/records#202]
Hi kennethreitz,

Thank you for the great work. I'm new to writing raw SQL queries in my Python app, and the wise people at Google recommend your library as a good place to start.

Give that this project lives inside the `archive` username, my question might be redundant. But is this library being maintained in 2020? Are you looking for maintainers? Is it safe to use for a greenfield project or would you recommend something else?

Thank you.

-- Sri

**Comment by Pk13055** [comment]
Anyone looking for a simple async, fast, postgresql client/wrapper, take a look at [asyncpg](https://github.com/MagicStack/asyncpg)

**Comment by lipi** [comment]
Judging from how a simple PR ( #172 ) not getting merged in 2 years I would say this project is abandoned.

**Comment by kennethreitz** [comment]
working on it now
