### ISSUE TITLE
This library may no longer be maintained, and many problems 1 year ago have not been dealt with

### ISSUE THREAD

**Issue by zhonghai9967** [kennethreitz/records#207]
Let's break up

**Comment by alik472** [comment]
Lets transer it to psf please

**Comment by ViCrack** [comment]
is there alternative project like this project?

**Comment by tym-xqo** [comment]
@ViCrack There are several. I personally maintain [sqla-raw](https://github.com/nerium-data/sqla-raw); the README.md there includes [links to a few alternatives](https://github.com/nerium-data/sqla-raw#alternatives-and-prior-art)

**Comment by kennell** [comment]
+1 for transferring this into the hands of a organization for further maintenance

**Comment by kennethreitz** [comment]
i pushed a release!
