### ISSUE TITLE
Records is not compatible with Python 3.8+

### ISSUE THREAD

**Issue by robstel** [kennethreitz/records#214]
records python3 is not compatible with new sqlalchemy release 1.4.0 (#208) https://github.com/kennethreitz/records/issues/208 
but versions of sqlalchemy older than 1.4.0 are not compatible with Python 3.8+: module 'time' has no attribute 'clock' in python3.8b1 #4731 https://github.com/sqlalchemy/sqlalchemy/issues/4731

**Comment by kennethreitz** [comment]
This should be fixed now!
