### ISSUE TITLE
sqlalchemy 2.0 support.

### ISSUE THREAD

**Issue by liudonghua123** [kennethreitz/records#218]
[sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) v2.0 is almost done, a lot of features like async/await are involved.

If this python library could support [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) v2.0, it's would be wonderful.

**Comment by kennethreitz** [comment]
v0.6.0 was just released, which does this!
