### ISSUE TITLE
Use Database() as context manager

### ISSUE THREAD

**Issue by mcdallas** [kennethreitz/records#25]
We could move 
```sh
self.db = psycopg2.connect(self.db_url, cursor_factory=BetterNamedTupleCursor)
```
to the \_\_enter\_\_ method and add a 

```sh
    def __exit__(self):
        self.db.close()
```    
so Database can be used with the __with__ keyword

example:
```sh
with records.Database('postgres://...') as db:
    data = db.query('select * from active_users') .all()
```

**Comment by kennethreitz** [comment]
Hmm, I like this idea.

**Comment by foresmac** [comment]
This causes whatever you're using to constantly connect and disconnect from the database. A more performant option would use a cursor for the context manager, and reconnect to the database if for whatever reason `db.closed == True`.

**Comment by andrew-tifon** [comment]
when creating a context manager, called the __init__, which opens the database and it remains open until the call __exit __ or until the end of the block with
does not work is that when you call __init___ otkravyetsya database and does not close until __exit__?

**Comment by mcdallas** [comment]
@foresmac well the idea is that if you want to maintain the connection you instantiate the class normally. If however you want to look something up on the fly, you can do it with two lines of code using _with_

**Comment by foresmac** [comment]
In that case, makes perfect sense as long as the caveats are documented.

**Comment by zhou929458522** [comment]
_**wow,it's great**_

**Comment by kennethreitz** [comment]
done
