### ISSUE TITLE
Bug with table headings

### ISSUE THREAD

**Issue by dorosch** [kennethreitz/records#30]
Database query:

``` Python
rows = db.query("select * from users")
```

if he does not return the headers of the table, the result:
![screenshot from 2016-02-10 09 27 24](https://cloud.githubusercontent.com/assets/13240952/12940264/882cae08-cfd8-11e5-99cc-12ac624780ea.png)
and if you try to export the data, there will be an error
![screenshot from 2016-02-10 09 28 48](https://cloud.githubusercontent.com/assets/13240952/12940297/b75c55f2-cfd8-11e5-9cde-1093adcffc45.png)
because the table did not return headers, and they are trying to take

``` Python
def dataset(self):
        """A Tablib Dataset representation of the ResultSet."""
        # Create a new Tablib Dataset.
        data = tablib.Dataset()

        # Set the column names as headers on Tablib Dataset.
        first = self[0]

        data.headers = first._fields
```

**Comment by kennethreitz** [comment]
How can I reproduce this? This doesn't seem like a very common occurrence. `select *` queries against the Postgres database I'm using contains description (column names).

**Comment by kennethreitz** [comment]
This library does currently assume that the results contain column names.

**Comment by vlcinsky** [comment]
Seems like bogus. As it is not clear how to reproduce such problem. Closing.
