### ISSUE TITLE
Add parameters for constructing the Database url

### ISSUE THREAD

**Issue by mcdallas** [kennethreitz/records#37]
Some people might not know about host url (I had to look it up), maybe we could use parameters to construct the connection url, something like:

```sh
class Database(object):
    """A Database connection."""

def __init__(self, host='localhost', port=5432, user=None, pass=None):
```

**Comment by kennethreitz** [comment]
`DATABASE_URL` is a pattern that I'd like to encourage. I'm not 100% against adding this functionality in the future, but for now, I think this is the way to go.
