### ISSUE TITLE
is there a way of create or update a record with a dictionary for data?

### ISSUE THREAD

**Issue by yaniaular** [kennethreitz/records#40]
By example: 

```python
dict_data = {'table': 'table_1', 'set': {'name': 'Peter', 'last_name' : 'Smith'}, 'where': [('id', '=', '4')] }
db.update(dict_data)
```

```python
dict_data = {'table': 'table_1', 'columns': {'name': 'Peter', 'last_name' : 'Smith'} }
db.create(dict_data)
```

I can be saying crazy. But it might be possible.

**Comment by kennethreitz** [comment]
You may be saying crazy. I like the concept, but this would be a fundamental change the functionality of Records, currently. I'm not saying that's a bad thing; I'm just saying that it needs to be very carefully considered.

**Comment by kennethreitz** [comment]
Currently the pitch of this library is "Just Write SQL". This would effectively stray away from that concept.

**Comment by yaniaular** [comment]
@kennethreitz Thanks for your response :blush:

**Comment by kennethreitz** [comment]
Thanks for the suggestion!
