### ISSUE TITLE
use Postgres.py under the hood

### ISSUE THREAD

**Issue by whit537** [kennethreitz/records#41]
Over in Gratipay-land we've got a library called [Postgres.py](https://postgres-py.readthedocs.org/) that has a very similar scope to Records-the-library (it has no CLI). It's been in production for three or four years, and as you [say](https://twitter.com/kennethreitz/status/698334100256460804), it's "much more robust" than Records from an API point of view. I know you're opinionated about API design. I believe Postgres.py's API is worthy (or nearly so) of the "for Humans" appellation (and I'm not sure I didn't actually run that by you at some point in the past ;-).

I like the Tablib integration and CLI that I see here on Records, and our APIs are pretty close.

@kennethreitz Would you be open to a PR that switches Records to use Postgres.py under the hood? I'd envision keeping the CLI exactly the same. I think we'd need to talk through API—what gets wrapped, what gets exposed, what might be upstreamed.

Waddya say? Up for collaborating? :-)

**Comment by whit537** [comment]
([Twitter context](https://twitter.com/whit537/status/698333810740502528))

**Comment by kennethreitz** [comment]
Honestly, my immediate reaction is "I'm not sure", leaning towards "no". 

Records, as it stands, is a very thin layer on top of psycopg2, which, for the feature set that Records currently provide, is a perfect fit. In other words, I don't think moving to something else would provide any benefit at this time. 

Also, that has been some consideration for adding support for other database backends. If we were to do this, it would likely be in the form of *using SQLAlchemy as a database driver*. So, relying on another Postgres library would

That being said, at the moment, I'm deciding to stick with Postgres-only support (mostly because of very subtle differences in the way querys can be expressed in SQLAlchemy). I'm reconsidering it constantly, though, so this is further reason to not make any big dependency commitments at this time.

**Comment by kennethreitz** [comment]
Just pushed the release built on top of SQLAlchemy :D

**Comment by whit537** [comment]
Alright. Good luck! :-)

**Comment by kennethreitz** [comment]
@whit537 :sob:

**Comment by whit537** [comment]
No worries. I think you just made DB-API 3.0, and I like it. :-)

**Comment by whit537** [comment]
P.S. I would be remiss not to note that @3kwa ported the basic API from Postgres.py for other databases  in https://github.com/3kwa/sql.

**Comment by 3kwa** [comment]
@kennethreitz must be a better brand in the Python sphere. Thought of you @whit537 when I saw records pop all over the place.

**Comment by whit537** [comment]
:-)

**Comment by kennethreitz** [comment]
I'm the Kanye West of Python.

(That's my Kanye impersonation)

**Comment by kennethreitz** [comment]
Well, we're much less in competition now that Records is powered by SQLAlchemy. So, the sky's the limit!

**Comment by whit537** [comment]
> Well, we're much less in competition now that Records is powered by SQLAlchemy.

Mmmm ... over here it feels like we're much less in competition because Records has already nuked Postgres.py and sql out of the water in terms of open-source mindshare.

![screen shot 2016-02-13 at 11 42 46 am](https://cloud.githubusercontent.com/assets/134455/13028776/06796ccc-d247-11e5-98c1-0cc7fe750c37.png)
![screen shot 2016-02-13 at 11 42 58 am](https://cloud.githubusercontent.com/assets/134455/13028777/067ac158-d247-11e5-9a49-6e5d7f6b2474.png)
![screen shot 2016-02-13 at 11 43 14 am](https://cloud.githubusercontent.com/assets/134455/13028778/067b5528-d247-11e5-964f-24b2239332d2.png)

I'm not gonna say that doesn't burn a little bit, but branding and community matter at least as much as code, and you're purty good at all three. :smile_cat: At the end of the day what *really* matters is that the Python community is finally getting a sane SQL API. :beers:

**Comment by kennethreitz** [comment]
`^L`

**Comment by 3kwa** [comment]
Wow does that mean sql is 1st in watch, star and fork :dancer:

**Comment by whit537** [comment]
> Wow does that mean sql is 1st in watch, star and fork :dancer:

Hah! [You're the best around](https://www.youtube.com/watch?v=oomCIXGzsR0)! :dancer: 

> `^L`

Yeah, I finally [ate crow](https://github.com/gratipay/aspen.py/issues/526) on Aspen recently as well. Over there I never got the code to the level of polish I wanted, but I was actually really proud of Postgres.py. It was well-designed, well-documented, well-tested, ported to Python 3 ... tight!

**Comment by whit537** [comment]
Hey! Here's another one called [Queries](https://github.com/gmr/queries) from @gmr. I found it on http://awesome-python.com/ after googling for "postgres python for humans."

> Queries is inspired by Kenneth Reitz's awesome work on requests.

Looks like it's older than Postgres.py ([initial commit](https://github.com/gmr/queries/commit/c519791a6ef9ea46bf8eb22f501ffeec61296106) on Queries is August 24, 2012, based on prior work; initial commit on Postgres.py is from Aug 7, 2013, based on internal Gittipay code going back to [at least](https://github.com/gratipay/gratipay.com/blob/61ebfccfb7ebf806a0341ffe6e3083bd5e8afb64/logstown/postgres.py) June 1, 2012).

@gmr Looks like you came in second! Or third, depending on how we're counting it. ;-)

![screen shot 2016-02-13 at 5 31 51 pm](https://cloud.githubusercontent.com/assets/134455/13030409/b7c92f6e-d277-11e5-9125-0374749bc153.png)

**Comment by whit537** [comment]
https://github.com/vinta/awesome-python/pull/567
https://github.com/vinta/awesome-python/pull/568
https://github.com/vinta/awesome-python/pull/569
