### ISSUE TITLE
automatically dereference when only one key/value

### ISSUE THREAD

**Issue by whit537** [kennethreitz/records#44]
Over in Postgres.py we [have](https://postgres-py.readthedocs.org/en/2.1.2/#tutorial) an API feature where we automatically dereference single-column queries. Do you want that feature, @kennethreitz? It would mean this:

```python
>>> db.query("select foo from bar").all()
[2, 4, 6, 8]
```

Instead of this:

```python
>>> db.query("select foo from bar").all()
[<Record "foo": 2>, <Record "foo": 4>, <Record "foo": 6>, <Record "foo": 8>]
```

**Comment by kennethreitz** [comment]
That's a cool feature!

I like our current behavior, though. I'd like to keep it as it is.
