### ISSUE TITLE
Support for SQLite

### ISSUE THREAD

**Issue by lucianmarin** [kennethreitz/records#5]
Support for SQLite should straight forward since DB-API interface is built-in.

**Comment by kennethreitz** [comment]
I haven't used the DB-API directly myself. What would the integration look like?

**Comment by MichaelMartinez** [comment]
Using the Sqlite standard lib is straightforward: here is some code I wrote while scraping Living Social for my wife. :smiling_imp: It is not the prettiest code out there, but it works... and a reason why a simple method to do this with Records will be highly requested. 

```python
# Start the DB
def init_db():
    con = sqlite3.connect("Living_Social.db")
    cur = con.cursor()
    cur.execute(
        '''CREATE TABLE IF NOT EXISTS deals (id INTEGER PRIMARY KEY, name TEXT, price_before REAL, price_after REAL, url TEXT UNIQUE, scrapetime text )''')
    con.commit()
    cur.close()
    con.close()


def save_to_db(deal_info):
    con = sqlite3.connect("Living_Social.db")
    cur = con.cursor()
    # Had to use OR IGNORE due scrape pulling down more than one listing
    # Using the URL as the Unique identifier because it contains the deal ID and we need it anyway
    cur.execute("INSERT OR IGNORE INTO deals (name, price_before, price_after, url, scrapetime) VALUES (?,?,?,?,?)", \
                [deal_info['name'], deal_info['price_before'], deal_info['price_after'], deal_info['url'], deal_info['scrapetime']])
    con.commit()
    cur.close()
    con.close()
``` 

As far as integration into records is concerned... no idea. :confused:

**Comment by lucianmarin** [comment]
You can simply check `DATABASE_URL` string and use `sqlite3.connect()` instead of `psycopg2.connect()`.

**Comment by kennethreitz** [comment]
It looks like the parameterization style is different. I'd have to take a closer look.

If we're going to support multiple databases, I think using SQLAlchemy as our driver would be the simplest choice.

**Comment by kennethreitz** [comment]
Currently, this library plans to support Postgres–only. That may change, but not now.

**Comment by kennethreitz** [comment]
*cough* support for sqlite has been added!

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

v0.4.0 includes support for all major databases. Enjoy!
