### ISSUE TITLE
iLIKE support?

### ISSUE THREAD

**Issue by dtb557** [kennethreitz/records#59]
Not a big deal, but why does `db.query('select * from papers where author iLIKE "%childress%"')` throw an error (specifically: `sqlite3.OperationalError: near "iLIKE": syntax error`). 

`db.query('select * from papers where LOWER(author) LIKE "%childress%"')` works fine, so this is a minor issue.

**Comment by timofurrer** [comment]
I think this is not an issue of `records` but `sqlalchemy` (or some underlying packages). I suggest to open the issue there..

**Comment by iurisilvio** [comment]
It is because sqlite does not support `ILIKE` operator.

https://www.sqlite.org/lang_expr.html

**Comment by dtb557** [comment]
I see, thanks for clarifying this for me, and thanks to the `records` team for making a great package!

**Comment by kennethreitz** [comment]
;)
