### ISSUE TITLE
Do I have to use SQL? Can I use the ORM in SQLalchemy? [proposed label question]

### ISSUE THREAD

**Issue by Logmytech** [kennethreitz/records#60]
I want to use ORM. I use SQLAlchemy only for the ORM. Does **_records_** support ORM or only SQL commands.

**Comment by kennethreitz** [comment]
Only SQL.

**Comment by iurisilvio** [comment]
@Logmytech FYI, records does not support ORM, but SQLAlchemy can build SQL expressions, compiling it to your database dialect.

http://docs.sqlalchemy.org/en/latest/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined
