### ISSUE TITLE
Gevent support

### ISSUE THREAD

**Issue by Sperryfreak01** [kennethreitz/records#61]
Does records support greenlets/gevent?  I had inserts working on my DB using records and then when i wrapped the code inside a greenlet spawn the code executes but the DB shows no writes.

**Comment by kennethreitz** [comment]
You would have to use a green-compatible database driver.

**Comment by Sperryfreak01** [comment]
thanks, thats what I am looking at now.

**Comment by Sperryfreak01** [comment]
I've never used SQLalchemy before so it took longer than I am proud to admit, but I got everything working.  

For anyone else who may need it in the future.
[https://github.com/hkwi/sqlalchemy_gevent](sqlalchemy_gevent)  

I used example 1 from the above library with Records:
db = records.Database('gevent_sqlite:///RecordsExample.db')

**Comment by kennethreitz** [comment]
@Sperryfreak01 nice find!
