### ISSUE TITLE
Is sqlalchemy an implementation detail?

### ISSUE THREAD

**Issue by Ayrx** [kennethreitz/records#63]
Currently, the only way I can see to catch things like foreign key constraint is to catch the `sqlalchemy.exc.IntegrityError` raised and handle it. However, this makes me uncomfortable since there is no indication if sqlalchemy is currently just an implementation detail or a core part of `records`.

Can I safely handle exceptions raised by sqlalchemy and call it a day or should I be worried about stuff breaking if sqlalchemy gets swapped out for something else? If no, is there an official way of catching errors raised by foreign key constraints?

**Comment by Ayrx** [comment]
@kennethreitz Can I have your take on this issue? Thanks!

**Comment by cal97g** [comment]
@kennethreitz @kennethreitz

**Comment by kennethreitz** [comment]
For now, it's a core part of records. I don't see that changing any time soon, if at all.

**Comment by Ayrx** [comment]
Thanks for the reply and thank you for another awesome library!
