### ISSUE TITLE
LastRowID

### ISSUE THREAD

**Issue by ikresoft** [kennethreitz/records#64]
How can I get last row id?

**Comment by ikresoft** [comment]
Solved, sorry :)

**Comment by PetaPetaPeta** [comment]
How did you end up solving this? I ended up going using something like:
`db = records.Database()
r = db.db.execute(insert_sql)
id = r._saved_cursor.lastrowid`
But I am not quite satisfied with it.

**Comment by ikresoft** [comment]
I am using MySql last_insert_id() function

**Comment by 36304099** [comment]
db.query("insert ....")
row=db.query("select last_insert_id() as id")
lastinsertid=row[0]['id']
