### ISSUE TITLE
Connection is not been closed

### ISSUE THREAD

**Issue by thiagoramos23** [kennethreitz/records#67]
Hi guys. I'm having trouble to close the connection with postgres. And the live connections always goes up.

I already implemented does methods here. But the connection is never closed nor reutilized.
`
    def **enter**(self):
        return self

```
def __exit__(self, exc, val, traceback):
    if self.db:
        self.db.close()
```

`

Could you tell me what I am doing wrong?

**Comment by mcdallas** [comment]
You close the connection with the .close() method

**Comment by drowolath** [comment]
Hello,
I do have the same issue with a postgresql database. I have Celery tasks in a queue that write to a postgresql database; even if I explicitly .close() the connections, netstat shows that the connections are still opened when all tasks are processed. I am not quite sure how to handle this.

**Comment by iurisilvio** [comment]
I think it's SQLAlchemy connection pooling working as expected.

It is possible to disable pooling, but I never tried do it with URL configuration (something like `?poolclass=None`).

http://docs.sqlalchemy.org/en/latest/core/pooling.html

**Comment by dmitrytokarev** [comment]
@iurisilvio thanks for the link!!! this worked for me:
```python
import records
from sqlalchemy.pool import NullPool
db = records.Database("postgresql://USER_NAME@localhost/DB_NAME", poolclass=NullPool)
db.close()
```

I used this to check for open connections to a DB:
after creating `db = records.Database(url, poolclass=NullPool)`:
```
$ psql -U postgres -c "SELECT datid,datname,pid,usesysid,usename,state,query FROM pg_stat_activity WHERE datname='DB_NAME';"

 datid |  datname  |  pid  | usesysid | usename  |        state        |              query               
-------+-----------+-------+----------+----------+---------------------+----------------------------------
 73233 | client032 | 23020 |       10 | postgres | idle in transaction | show standard_conforming_strings
(1 row)
```

After calling `db.close()`
```
$ psql -U postgres -c "SELECT datid,datname,pid,usesysid,usename,state,query FROM pg_stat_activity WHERE datname='DB_NAME';"
WARNING: password file "/home/dtokarev/.pgpass" has group or world access; permissions should be u=rw (0600) or less
 datid | datname | pid | usesysid | usename | state | query 
-------+---------+-----+----------+---------+-------+-------
(0 rows)
```
yay! no connections!

**Comment by RazerM** [comment]
This should be re-opened until #98 is merged. Records' `close()` behaviour is broken unless user passes `poolclass=NullPool`.
