### ISSUE TITLE
Delete rows

### ISSUE THREAD

**Issue by sephib** [kennethreitz/records#68]
Hi,
My script is hanging once I try to delete some rows
`sql_clause = 'DELETE FROM {0} WHERE interval_start = :interval_datetime'.format(self.name)
self.database.query(sql_clause, interval_datetime=interval_datetime)`

where database is a records.Database object.

How can you use records to delete rows?
thx
Sephi

**Comment by vlcinsky** [comment]
Delete is already supported.

e.g.
```
import records

db = db.Database()  # assuming DATEBASE_URL env. variable points to proper sqlite url
db.query("delete from users")
```

worked for me. Similarly using `db.query_file`.

Closing.
