### ISSUE TITLE
get_table_names implementation

### ISSUE THREAD

**Issue by RazerM** [kennethreitz/records#74]
The implementation for [`get_table_names`](https://github.com/kennethreitz/records/blob/133532bdc300e551c2aeecf4423df7fab9b9e4fc/records.py#L224) is odd.

The following steps are executed every time, making the function much more expensive than it needs to be:
1. a new engine is created rather than using the existing one to check out a connection
2. a declarative base is created just to use its metadata, which is better created using `sqlalchemy.MetaData()`
3. The whole database schema is reflected just to get the table names.

The fix would look something like:

```
from sqlalchemy import inspect

def __init__(...):
    engine = create_engine(...)
    self.db = engine.connect()
    self._engine = engine

def get_table_names():
    return inspect(self._engine).get_table_names()
```

**Comment by dmitrytokarev** [comment]
Additionally with Postgres current implementation of `get_table_names()` leaves open connection even after calling `db.close()`:
```
>>> import sh
>>> from sqlalchemy.pool import NullPool
>>> import records
>>> 
>>> psql = sh.Command('psql')
>>> cmd = ['-U', 'postgres', '-c', "SELECT datid,datname,pid,usesysid,usename,state,query FROM pg_stat_activity WHERE datname='client008';"]
>>> psql(cmd) # check open connections
 datid | datname | pid | usesysid | usename | state | query 
-------+---------+-----+----------+---------+-------+-------
(0 rows)


>>> db = records.Database("postgresql://postgres@localhost/client008", poolclass=NullPool)
>>> psql(cmd)  # 1 connection as expected
 datid |  datname  | pid  | usesysid | usename  |        state        |              query               
-------+-----------+------+----------+----------+---------------------+----------------------------------
 50380 | client008 | 4107 |       10 | postgres | idle in transaction | show standard_conforming_strings
(1 row)


>>> tables = db.get_table_names()
>>> psql(cmd)  # 2 connections!!!!
 datid |  datname  | pid  | usesysid | usename  |        state        |              query               
-------+-----------+------+----------+----------+---------------------+----------------------------------
 50380 | client008 | 4107 |       10 | postgres | idle in transaction | show standard_conforming_strings
 50380 | client008 | 4245 |       10 | postgres | idle                | ROLLBACK
(2 rows)

>>> db.close()  # let's close this connection
>>> db.open
False
>>> psql(cmd)  # still 1 connection is live!!!
 datid |  datname  | pid  | usesysid | usename  | state |  query   
-------+-----------+------+----------+----------+-------+----------
 50380 | client008 | 4245 |       10 | postgres | idle  | ROLLBACK
(1 row)
```

**Comment by dmitrytokarev** [comment]
I tried @RazerM 's suggestion and it works great: faster and doesn't create additional connections to DB.
@RazerM i encourage you to open PR to fix `get_table_names()`

**Comment by RazerM** [comment]
@dmitrytokarev Sure I'll submit a PR, I just never got round to it since I don't use Records.

Re: the connection being left open: yes, the problem is that the `Database` class creates an engine with a pool and upon `.close` just returns it to the pool. I'll also submit a PR to use `NullPool` by default, since Records provides no way to access it.
