### ISSUE TITLE
cli output to .xls format is cast to a string in Python 3

### ISSUE THREAD

**Issue by tanyaschlusser** [kennethreitz/records#78]
If, when using Python 3, you try to output to Excel using the command line interface:

``` shell
records 'select * from T' xls > output.xls
```

the file _output.xls_ will not be binary-formatted, but will instead be a string beginning with b'\xd0\x...etc' because the byte string is cast to a string by Python 3's print function.  Here's a quick but ugly patch. But maybe this should be imported as a short function from tablib instead. If so, I can add an issue to tablib.

This is the function that could either go here or in tablib:

``` python
from sys import stdout

def print_bytes(content):
    try:
        stdout.buffer.write(content)
    except AttributeError:
        stdout.write(content)
```

And it can be used inside the `cli()` function:

``` python
     # Print results in desired format.
     if arguments['<format>']:
        ## print(rows.export(arguments['<format>']))
        print_bytes(rows.export(arguments['<format>']))
     else:
         print(rows.dataset)
```

**Comment by vlcinsky** [comment]
PR #136 is using (slightly modified) version of above code. Tested on python 2.7 and 3.6.
