### ISSUE TITLE
should use self.db or self._db

### ISSUE THREAD

**Issue by Allianzcortex** [kennethreitz/records#81]
Hello,Kennethreitz,Now I'm learning your code to try to write Pythonic code :-D

One small question is whether should use self._db instead self.db in `class Database`,because we don't need it to expose to users,just use in internal.

Thanks for your help~~

**Comment by alan-bush** [comment]
I think so

**Comment by timofurrer** [comment]
Well, I think it's fine as it is right now. `self._db` is anyway just *best practice* (or more what a lot of people agreed to when trying to make something protected - private would be double underscores without having them as postfix)

However, sometimes you really want to access the database engine directly so having `self.db` available prevents linters from complaining which is pretty convenient.
