### ISSUE TITLE
records.Database UNIX socket connection string

### ISSUE THREAD

**Issue by timkofu** [kennethreitz/records#86]
What's the correct connection string for connecting to PostgreSQL via a UNIX socket?

**Comment by Xarrow** [comment]
connect string like this :
```python
 postgresql+pypostgresql://user:password@host:port/dbname[?key=value&key=value...]
```
you can get this refer by [sqlAlchemy](http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#module-sqlalchemy.dialects.postgresql.pypostgresql)

**Comment by timkofu** [comment]
That's for a TCP/IP connection. Got somewhere showing a Unix socket connection string? Haven't found it in the docs so far.

**Comment by timofurrer** [comment]
It's in the docs right [here](http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#unix-domain-connections)

If you are using `psycopg2` you can omit the `host` in your connection string. With that sqlalchemy will pass `None` as the host argument to `psycopg2` which will connect to the postgres server via UNIX socket.

**Comment by timkofu** [comment]
Works. Thank you.

**Comment by leafonsword** [comment]
Hope records's readme has some example about connecting to MySQL or PG,;I was looking for a long time then found this issue then knows how to connect to MySQL

**Comment by Xarrow** [comment]
example for connecting mysql by using “pymysql” driver，
```
records.DATABASE_URL = "mysql+pymysql://user:password@host:port/db"
db = records.Database(echo=True)
```

i think record is based on SQLAlchemy , you can refer to  the official document of SQLAlchemy  and make expand

**Comment by leafonsword** [comment]
@Xarrow 
Thx, your example about PyMySQL works well!
