### ISSUE TITLE
possible to connect to SQLCipher encrypted DB?

### ISSUE THREAD

**Issue by sk-gara** [kennethreitz/records#89]
As I understand, it's not possible, but maybe I missed something?

**Comment by timofurrer** [comment]
You can connect to every database which is supported by `sqlalchemy`. 

You can use SQLCipher to encrypt SQLite databases with sqlalchemy - have a look at: http://docs.sqlalchemy.org/en/latest/dialects/sqlite.html#module-sqlalchemy.dialects.sqlite.pysqlcipher

**Comment by sk-gara** [comment]
Thanks, works with `sqlite + psqlcipher`!
