### ISSUE TITLE
Support for Oracle (cx_Oracle)?

### ISSUE THREAD

**Issue by tyrdare** [kennethreitz/records#9]
Saw requests for MySQL and SQLite, thought I'd throw in a request for Oracle.

**Comment by Anachron** [comment]
I would also love some oracle support!

**Comment by tyrdare** [comment]
Looks like cx_Oracle would have to have an implementation of a DictCursor, like psycopg2.  The system tables are a bit different too, unsurprisingly.

**Comment by uetoyo** [comment]
Can we use py(py)odbc?

**Comment by kennethreitz** [comment]
Currently, this library plans to support Postgres–only. That may change, but not now.

**Comment by kennethreitz** [comment]
*cough* support for oracle has been added!

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

v0.4.0 includes support for all major databases. Enjoy!
