### ISSUE TITLE
CLI format parameter should be optional but is required

### ISSUE THREAD

**Issue by TomFaulkner** [kennethreitz/records#90]
It appears the docopt docstring for the cli function is incorrect.
Line 327 has format as a required parameter. Lines 385-389 check if arguments['<format>'] is set and pritns rows.dataset if they are not, which would indicate that the format parameter should be optional. Further, the example on line 344 lacks the format argument.

Suggested fix is to make line 327 as follows:
Line 327: records < query > [< format >] [ < params > ...] [--url = < url >]

Current:
Line 327: records < query > < format > [ < params > ...] [--url = < url >]

Line 385-389:
    # Print results in desired format.
    if arguments['<format>']:
        print(rows.export(arguments['<format>']))
    else:
        print(rows.dataset)

Edit:
I submitted a pull request with this change.

**Comment by vlcinsky** [comment]
PR  #133 shall fix this.

**Comment by vlcinsky** [comment]
PR #134 merged, shall be fixed now.
